test = {
    "Lawn Mowing and Trimming": 160,
    "Interior Design": 152,
    "Handyman": 129,
    "Roof Repair or Maintenance": 204,
    "General Contracting": 123,
    "Personal Training": 283,
    "Massage Therapy": 280,
    "Life Coaching": 546,
    "Private Yoga Instruction": 287,
    "Private Pilates Instruction": 285,
    "Nutritionist": 281,
    "Dog Walking": 298,
    "Pet Sitting": 300,
    "Aquarium Services": 292,
    "Cat Grooming": 293,
    "Statistical Data Analysis": 354,
    "Accounting": 302,
    "Corporate Law Attorney": 525,
    "Logo Design": 521,
    "Computer Repair": 564,
    "Business Tax Preparation": 306,
    "DJ": 386,
    "Wedding Officiant": 441,
    "Wedding and Event Catering": 443,
    "Wedding and Event Makeup": 447,
    "Photo Booth Rental": 415,
    "Bartending": 372,
    "Singing Lessons": 500,
    "Piano Lessons": 484,
    "Private Self Defense Lessons": 490,
    "Reading and Writing Tutoring": 494,
    "Math Tutoring": 479,
    "Above Ground Swimming Pool Installation": 34,
    "Air Quality and Environmental Testing": 35,
    "Appliance Installation": 563,
    "Appliance Repair or Maintenance": 37,
    "Architectural Services": 38,
    "Artificial Turf Installation": 39,
    "Asbestos Removal": 40,
    "Asphalt Installation": 41,
    "Asphalt Repair and Maintenance": 42,
    "Basement Finishing or Remodeling": 43,
    "Bathroom Remodel": 44,
    "Bed Bug Extermination": 45,
    "Brick or Stone Repair": 46,
    "Cabinet Installation": 47,
    "Cabinet Painting": 48,
    "Cabinet Refinishing and Repair": 49,
    "Cabinetry": 50,
    "Carpet Cleaning": 51,
    "Carpet Installation": 52,
    "Carpet Removal": 53,
    "Carpet Repair or Partial Replacement": 54,
    "Central Air Conditioning Installation or Replacement": 55,
    "Central Air Conditioning Repair or Maintenance": 56,
    "Circuit Breaker Panel or Fuse Box Installation": 57,
    "Circuit Breaker Panel or Fuse Box Repair": 58,
    "Closet Remodel": 59,
    "Closet and Shelving System Installation": 60,
    "Commercial Carpet Cleaning": 61,
    "Commercial Cleaning": 62,
    "Concrete Installation": 63,
    "Concrete Removal": 64,
    "Concrete Repair and Maintenance": 65,
    "Construction Services": 66,
    "Countertop Installation": 67,
    "Countertop Repair or Maintenance": 68,
    "Custom Cabinet Building": 69,
    "Custom Furniture Building": 70,
    "Deck Staining and Sealing": 71,
    "Deck or Porch Remodel or Addition": 72,
    "Deck or Porch Repair": 73,
    "Demolition Services": 74,
    "Dishwasher Installation": 75,
    "Door Installation": 76,
    "Door Repair": 77,
    "Drywall Installation and Hanging": 78,
    "Drywall Repair and Texturing": 79,
    "Duct and Vent Cleaning": 80,
    "Duct and Vent Installation or Removal": 81,
    "Duct and Vent Repair": 82,
    "Dumpster Rental": 83,
    "Electrical and Wiring Repair": 84,
    "Emergency Plumbing": 85,
    "Engraving": 511,
    "Epoxy Floor Coating": 87,
    "Excavation Services": 88,
    "Exterior Painting": 89,
    "Fan Installation": 90,
    "Faux Finishing or Painting": 91,
    "Fence Painting": 92,
    "Fence and Gate Installation": 93,
    "Fence and Gate Repairs": 94,
    "Finish Carpentry": 95,
    "Fireplace and Chimney Cleaning or Repair": 96,
    "Fireplace and Chimney Installation": 97,
    "Fitness Equipment Assembly": 98,
    "Floor Cleaning": 99,
    "Floor Installation or Replacement": 100,
    "Floor Painting or Coating": 101,
    "Floor Polishing": 102,
    "Floor Repair": 103,
    "Foundation Repair": 104,
    "Framing Carpentry": 105,
    "Full Service Lawn Care": 106,
    "Furniture Assembly": 107,
    "Furniture Delivery": 108,
    "Furniture Moving and Heavy Lifting": 109,
    "Furniture Refinishing": 110,
    "Furniture Repair": 111,
    "Furniture Upholstery": 112,
    "Garage Addition or Remodel": 113,
    "Garage Door Installation or Replacement": 114,
    "Garage Door Repair": 115,
    "Garage, Basement or Attic Cleaning": 116,
    "Garbage Disposal Installation": 117,
    "Garbage Disposal Repair": 118,
    "Gardening": 119,
    "Gas Line Installation": 120,
    "Gazebo Installation and Construction": 121,
    "General Carpentry": 122,
    "Generator Installation": 124,
    "Generator Repair": 125,
    "Gutter Cleaning and Maintenance": 126,
    "Gutter Installation or Replacement": 127,
    "Gutter Repair": 128,
    "Hardwood Floor Refinishing": 130,
    "Heating System Installation or Replacement": 131,
    "Heating System Repair or Maintenance": 132,
    "Holiday Lighting Installation and Removal": 133,
    "Home Inspection": 134,
    "Home Modification for Accessibility": 135,
    "Home Organizing": 136,
    "Home Remodeling": 137,
    "Home Security System Repair": 138,
    "Home Security and Alarms Install": 139,
    "Home Staging": 140,
    "Home Theater System Installation or Replacement": 141,
    "Home Theater System Repair or Service": 142,
    "Home Waterproofing": 143,
    "Hot Tub Moving": 144,
    "Hot Tub and Spa Cleaning and Maintenance": 145,
    "Hot Tub and Spa Installation": 146,
    "Hot Tub and Spa Repair": 147,
    "House Cleaning": 148,
    "House Sitting": 545,
    "In-Ground Swimming Pool Construction": 150,
    "Insulation Installation or Upgrade": 151,
    "Interior Painting": 153,
    "Junk Removal": 154,
    "Kitchen Remodel": 155,
    "Land Clearing": 156,
    "Land Leveling and Grading": 157,
    "Land Surveying": 158,
    "Lawn Mower Repair": 159,
    "Lighting Installation": 161,
    "Local Moving (under 50 miles)": 162,
    "Lock Installation and Repair": 163,
    "Long Distance Moving": 164,
    "Masonry Construction Services": 165,
    "Metalwork": 166,
    "Mold Inspection and Removal": 167,
    "Mulching": 168,
    "Muralist": 169,
    "New Home Construction": 170,
    "Odor Removal": 171,
    "Office Moving": 172,
    "Outdoor Landscaping and Design": 173,
    "Outdoor Mosquito Control Services": 174,
    "Outdoor Pesticide Application": 175,
    "Packing and Unpacking": 176,
    "Paint Removal": 177,
    "Patio Cover and Awning Services": 178,
    "Patio Remodel or Addition": 179,
    "Pest Control Services": 180,
    "Pest Inspection": 181,
    "Piano Moving": 182,
    "Picture Hanging and Art Installation": 183,
    "Plastering": 184,
    "Play Equipment Construction and Assembly": 185,
    "Plumbing Drain Repair": 186,
    "Plumbing Inspection": 187,
    "Plumbing Pipe Installation or Replacement": 188,
    "Plumbing Pipe Repair": 189,
    "Pool Table Moving": 190,
    "Pool Table Repair Services": 569,
    "Popcorn Texture Removal": 192,
    "Powder Coating": 514,
    "Pressure Washing": 194,
    "Property Management": 195,
    "Radon Mitigation": 537,
    "Railing Installation or Remodel": 197,
    "Real Estate Agent Services": 198,
    "Real Estate Appraisal": 199,
    "Rodent and Animal Removal": 200,
    "Roof Cleaning": 201,
    "Roof Inspection": 202,
    "Roof Installation or Replacement": 203,
    "Room Remodel": 205,
    "Rug Cleaning": 206,
    "Satellite Dish Services": 207,
    "Screen Installation or Replacement": 208,
    "Septic System Installation or Replacement": 209,
    "Septic System Repair, Maintenance or Inspection": 210,
    "Shower and Bathtub Installation or Replacement": 211,
    "Shower and Bathtub Repair": 212,
    "Shrub Trimming and Removal": 213,
    "Siding Installation": 214,
    "Siding Removal": 215,
    "Siding Repair": 216,
    "Sink or Faucet Installation or Replacement": 217,
    "Sink or Faucet Repair": 218,
    "Smart Home Installation or Repair": 219,
    "Snow Plowing": 220,
    "Sod Installation": 221,
    "Solar Panel Cleaning": 222,
    "Solar Panel Installation and Repair": 223,
    "Sound Proofing": 224,
    "Sprinkler and Irrigation System Installation": 225,
    "Sprinkler and Irrigation System Repair and Maintenance": 226,
    "Stair Installation, Remodel, or Repair": 227,
    "Structural Engineering Services": 228,
    "Stucco Application": 229,
    "Stucco Repair": 230,
    "Sump Pump Installation or Replacement": 231,
    "Swimming Pool Cleaning, Maintenance, and Inspection": 232,
    "Swimming Pool Inspection": 233,
    "Swimming Pool Removal": 234,
    "Swimming Pool Repair": 235,
    "Switch and Outlet Installation": 236,
    "Switch and Outlet Repair": 237,
    "TV Mounting": 238,
    "TV Repair Services": 239,
    "Termite Control Services": 240,
    "Termite Inspection": 241,
    "Thermostat Installation or Repair": 242,
    "Tile Installation and Replacement": 243,
    "Tile Repair": 244,
    "Tile and Grout Cleaning": 245,
    "Toilet Installation or Replacement": 246,
    "Toilet Repair": 247,
    "Tree Planting": 248,
    "Tree Stump Grinding and Removal": 249,
    "Tree Trimming and Removal": 250,
    "Trim or Molding Installation": 251,
    "Upholstery and Furniture Cleaning": 252,
    "Wallpaper Installation or Repair": 253,
    "Wallpaper Removal": 254,
    "Water Damage Cleanup and Restoration": 255,
    "Water Feature Installation": 256,
    "Water Feature Repair and Maintenance": 257,
    "Water Heater Installation or Replacement": 258,
    "Water Heater Repair or Maintenance": 259,
    "Water Treatment Repair or Maintenance": 260,
    "Water Treatment System Installation or Replacement": 261,
    "Weatherization": 262,
    "Weeding": 263,
    "Well System Work": 264,
    "Window Cleaning": 265,
    "Window Installation": 266,
    "Window Repair": 267,
    "Window Tinting": 268,
    "Window Treatment Installation or Repair": 269,
    "Window, Wall, or Portable AC Repair or Maintenance": 270,
    "Wiring Installation": 271,
    "Alternative Healing": 272,
    "Astrology Reading": 542,
    "Facial Treatments": 274,
    "Family Counseling": 543,
    "Health and Wellness Coaching": 276,
    "Hypnotherapy": 277,
    "Marriage and Relationship Counseling": 279,
    "Palm Reading": 548,
    "Physical Therapy": 284,
    "Private Tai Chi Instruction": 286,
    "Spiritual Counseling": 550,
    "Tarot Card Reading": 551,
    "Therapy and Counseling": 290,
    "Animal Training and Behavior Modification (Non-canine)": 291,
    "Dog Daycare": 294,
    "Dog Fence Installation": 295,
    "Dog Grooming": 296,
    "Dog Training": 297,
    "Pet Boarding": 299,
    "3D Modeling": 301,
    "Administrative Support": 303,
    "Animation": 517,
    "Business Consulting": 305,
    "Contracts Attorney": 524,
    "Court Interpreting": 526,
    "Criminal Defense Attorney": 311,
    "DUI Attorney": 312,
    "Data Recovery Service": 565,
    "Disability Attorney": 527,
    "Divorce Attorney": 315,
    "E-commerce Consulting": 316,
    "Electronic Machine Repair": 317,
    "Engineering and Technical Design": 518,
    "Estate Attorney": 528,
    "Exercise Equipment Repair": 566,
    "Family Law Attorney": 321,
    "Genealogy": 544,
    "Graphic Design": 519,
    "Illustrating": 520,
    "Immigration Attorney": 529,
    "Individual Tax Preparation": 326,
    "Intellectual Property Attorney": 530,
    "International Law Attorney": 531,
    "Labor and Employment Attorney": 532,
    "Legal Document Preparation": 533,
    "Marketing": 332,
    "Mediation": 547,
    "Mobile Design": 334,
    "Network Support Services": 567,
    "Notarization": 336,
    "Payroll Services": 337,
    "Personal Bankruptcy Attorney": 338,
    "Personal Financial Planning": 339,
    "Personal Injury Attorney": 535,
    "Phone or Tablet Repair": 568,
    "Presentation Design": 522,
    "Printer and Copier Repair": 570,
    "Private Investigation": 549,
    "Process Serving": 536,
    "Project Management": 346,
    "Public Relations": 347,
    "Real Estate Attorney": 538,
    "Recruiting": 349,
    "Resume Writing": 571,
    "Security and Body Guard Services": 351,
    "Social Media Marketing": 352,
    "Software Development": 523,
    "Tax Attorney": 539,
    "Telemarketing and Telesales Services": 356,
    "Traffic Law Attorney": 540,
    "Translation": 572,
    "Virus Removal Services": 359,
    "Web Design": 360,
    "Web Hosting": 361,
    "Wills and Estate Planning": 541,
    "Writing and Editing Services": 363,
    "AV Equipment Rental for Events": 364,
    "Aerial Photography": 553,
    "Alterations, Tailoring, and Clothing Design": 366,
    "Animal Show Entertainment": 367,
    "Audio Recording": 368,
    "Balloon Decorations": 369,
    "Balloon Twisting": 370,
    "Barbecue and Grill Services": 371,
    "Boudoir Photography": 554,
    "Bounce House and Party Inflatables Rental": 374,
    "Bridal Stylist": 375,
    "Calligraphy": 376,
    "Candy Buffet Services": 377,
    "Caricaturing": 378,
    "Charter Bus Rental": 379,
    "Circus Entertainment": 380,
    "Clown Entertainment": 381,
    "Comedy Entertainment": 382,
    "Commercial Photography": 555,
    "Costumed Character Entertainment": 384,
    "Custom Airbrushing": 509,
    "Dance Entertainment": 387,
    "Embroidery": 510,
    "Engagement Photography": 556,
    "Event Florist": 390,
    "Event Help and Wait Staff": 391,
    "Event Planning": 392,
    "Event Security & Bouncer Services": 393,
    "Face Painting": 394,
    "Fishing Trip Guide Services": 395,
    "Food Truck or Cart Services": 396,
    "Games and Concession Rental": 397,
    "Hair Coloring and Highlights": 398,
    "Headshot Photography": 557,
    "Henna Tattooing": 400,
    "Impersonating": 401,
    "Jewelry Services": 402,
    "Karaoke Machine Rental": 403,
    "Limousine and Chauffeur Services": 404,
    "MC and Host Services": 405,
    "Magician": 406,
    "Motivational Speaking": 407,
    "Music Entertainment": 408,
    "Nature Photography": 558,
    "Party Bus Rental": 410,
    "Party Favors": 411,
    "Pastry Chef and Cake Making Services": 412,
    "Personal Chef": 413,
    "Pet Photography": 559,
    "Photo Editing, Scanning and Restoration": 416,
    "Portrait Artistry": 513,
    "Portrait Photography": 560,
    "Quilting and Crochet": 419,
    "Real Estate and Architectural Photography": 420,
    "Scrapbooking": 515,
    "Singing Telegram": 422,
    "Sommelier Services & Lessons": 423,
    "Songwriting": 516,
    "Sports Photography": 561,
    "Tarot and Psychic Reader Entertainment": 426,
    "Temporary Tattoo Artistry": 427,
    "Travel Agency Services": 428,
    "Valet Parking": 429,
    "Ventriloquist & Puppet Entertainment": 430,
    "Video Booth Rental": 431,
    "Video Editing": 562,
    "Video Production": 433,
    "Video Streaming and Webcasting Services": 434,
    "Video Transfer Services": 435,
    "Wardrobe Consulting": 552,
    "Wedding Cakes": 437,
    "Wedding Coordination": 438,
    "Wedding Dance Lessons": 439,
    "Wedding Florist": 440,
    "Wedding Planning": 442,
    "Wedding and Event Decorating": 444,
    "Wedding and Event Hair Styling": 445,
    "Wedding and Event Invitations": 446,
    "Wedding and Event Photography": 448,
    "Wedding and Event Venue Rental": 449,
    "Wedding and Event Videography": 450,
    "Wine Tastings and Tours": 451,
    "Acting Lessons": 452,
    "Arabic Lessons": 453,
    "Audio Production Lessons": 454,
    "Banjo Lessons": 455,
    "Baseball Lessons": 456,
    "Basketball Lessons": 457,
    "Bass Guitar Lessons": 458,
    "CPR and First Aid Training": 459,
    "Cello Lessons": 460,
    "Chess Lessons": 461,
    "College Admissions Counseling": 462,
    "Computer Lessons": 463,
    "Drawing Lessons": 464,
    "Driving Lessons": 465,
    "Drum Lessons": 466,
    "ESL (English as a Second Language) Lessons": 467,
    "Flute Lessons": 468,
    "French Lessons": 469,
    "German Lessons": 470,
    "Golf Lessons": 471,
    "Graphic Design Instruction": 472,
    "Guitar Lessons": 473,
    "Italian Lessons": 474,
    "Japanese Lessons": 475,
    "Korean Lessons": 476,
    "Makeup Artistry Lessons": 477,
    "Mandarin Lessons": 478,
    "Meditation Instruction": 480,
    "Music Theory Lessons": 481,
    "Painting Lessons": 482,
    "Photography Lessons": 483,
    "Piano Tuning": 485,
    "Portuguese Lessons": 486,
    "Private Cooking Lessons": 487,
    "Private Dance Lessons": 488,
    "Private Horseback Riding Lessons": 489,
    "Private Swim Lessons": 491,
    "Private Tennis Instruction": 492,
    "Public Speaking Lessons": 493,
    "Reiki Lessons": 495,
    "Saxophone Lessons": 496,
    "Science Tutoring": 497,
    "Sewing Lessons": 498,
    "Sign Language Lessons": 499,
    "Soccer Lessons": 501,
    "Social Sciences Tutoring": 502,
    "Softball Lessons": 503,
    "Spanish Lessons": 504,
    "Test Prep Services": 505,
    "Violin Lessons": 506,
    "Voice Over Lessons": 507,
    "Volleyball Lessons": 508,
    nan: 573,
}
